# Generated by Django 5.0.14 on 2025-08-06 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('uploaded_title', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('compared_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compare.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
