# Generated by Django 5.1.4 on 2024-12-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='books/')),
            ],
        ),
    ]
