# Generated by Django 5.1.4 on 2024-12-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_auto_20241217_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
